basePath: /
host: localhost:8000
info:
  contact:
    email: support@medihub.com
    name: API Support
  description: This is the API documentation for the Medihub application.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Medihub API
  version: "1.0"
paths: {}
swagger: "2.0"
